gpu_id: [0]

exp_name: LaRa/release-test
n_views: 1

model:
    encoder_backbone: 'dinov2_vits14' # ['vit_small_patch16_224.dino','vit_base_patch16_224.dino', 'dinov2_vits14']

    n_groups: [4]  # n_groups for local attention
    n_offset_groups: 16     # offset radius of 1/n_offset_groups of the scene size

    K: 8  # primitives per-voxel
    sh_degree: 1    # view dependent color

    # num_layers: 6 # 12
    num_heads: 16

    view_embed_dim: 32
    embedding_dim: 128

    label_in_channels: 128
    label_out_channels: 384

    vol_feat_reso: 16
    vol_embedding_reso: 16

    vol_embedding_out_dim: 80

    coarse_mlp_layers: 3

    img_feats_avg: True

    # ckpt_path: logs/LaRa/release-test/vol_render_epoch=599.ckpt # specify a ckpt path if you want to continue training  

# point_e:
#     cond_drop_prob: 0.1
#     heads: 8
#     init_scale: 0.25
#     layers: 6
#     n_ctx: 1024
#     input_channels: 128
#     output_channels: 3
#     time_token_cond: True
#     token_cond: True
#     width: 256
#     dit_block_depth: 4

triplane_e:
    cond_drop_prob: 0.1
    heads: 8
    init_scale: 0.25
    layers: 6
    n_ctx: 256
    embedding_channels: 128
    input_channels: 384
    output_channels: 384
    time_token_cond: True
    token_cond: True
    width: 256
    dit_block_depth: 4

train_dataset:
    dataset_name: custom_preload # shapenet_temp housecat6d
    # data_root: dataset/gobjaverse/gobjaverse.h5, /mnt/hdd/lara_data/dataset/Co3D/co3d_teddybear.h5, /home/lu/project/LaRa/housecat_objects_instances, /mnt/hdd/lara_data/dataset/housecat6d
    data_root: /home/q672126/project/omni3d/single #/home/q672126/project/anything6d/gso_renders
    split: train
    img_size: [420, 420] # image resolution, [852,1096]
    n_group: ${n_views}
    voxel_reso: 16
    n_scenes: 42
    load_normal: True
    positional_labelling: False
    clip_labelling: True
    labelling_dimension: 128
    max_occlusion_ratio: 0.9

test_dataset:
    dataset_name: custom_preload # shapenet_temp housecat6d
    # data_root: dataset/gobjaverse/gobjaverse.h5, /mnt/hdd/lara_data/dataset/Co3D/co3d_teddybear.h5, /home/lu/project/LaRa/housecat_objects_instances, /mnt/hdd/lara_data/dataset/housecat6d
    data_root: /home/q672126/project/omni3d/single #/home/q672126/project/anything6d/gso_val
    split: test
    img_size: [420, 420]
    n_group: ${n_views}
    voxel_reso: 16
    n_scenes: 42
    load_normal: True
    positional_labelling: False
    clip_labelling: True
    labelling_dimension: 128
    max_occlusion_ratio: 0.9

train:
    batch_size: 4
    lr: 1e-4
    beta1: 0.9
    beta2: 0.95
    weight_decay: 0.05
    # betas: [0.9, 0.95]
    warmup_iters: 10
    n_epoch: 30000
    limit_train_batches: 1.0 # 0.2
    limit_val_batches: 1.0 # 0.02
    check_val_every_n_epoch: 20
    log_train_every_n_step: 20
    start_save: 0
    use_rand_views: False
test:
    batch_size: 4
    log_val_every_n_step: 1

logger: 
    name: wandb
    dir: logs/${exp_name}
