gpu_id: [0]

exp_name: LaRa/release-test
n_views: 1
voxel_reso: 16

model:
    encoder_backbone: 'dinov2_vits14' # ['vit_small_patch16_224.dino','vit_base_patch16_224.dino', 'dinov2_vits14']

    n_groups: [4]  # n_groups for local attention
    # n_offset_groups: 32     # offset radius of 1/n_offset_groups of the scene size

    K: 16  # primitives per-voxel
    sh_degree: 1    # view dependent color

    # num_layers: 6 # 12
    num_heads: 16

    view_embed_dim: 32
    embedding_dim: 128

    label_in_channels: 128
    label_out_channels: 384

    # vol_feat_reso: 32
    vol_embedding_reso: ${voxel_reso}

    vol_embedding_out_dim: 80

    coarse_mlp_layers: 3

    img_feats_avg: True

    scene_size: 0.5
    opacity_shift: -2.1729
    scaling_shift: -4.5

    opacity_threshold: 0.02

    # ckpt_path: logs/LaRa/release-test/oclu-fine-16/vol_render_epoch=3999.ckpt # specify a ckpt path if you want to continue training  

# point_e:
#     cond_drop_prob: 0.1
#     heads: 8
#     init_scale: 0.25
#     layers: 6
#     n_ctx: 1024
#     input_channels: 128
#     output_channels: 3
#     time_token_cond: True
#     token_cond: True
#     width: 256
#     dit_block_depth: 4

triplane_e:
    cond_drop_prob: 0.1
    heads: 6
    init_scale: 0.25
    layers: 6
    # n_ctx: 256
    embedding_channels: 128
    input_channels: 384
    output_channels: 384
    time_token_cond: True
    token_cond: True
    width: 256
    dit_block_depth: 4

train_dataset:
    dataset_name: custom # shapenet_temp housecat6d
    data_root: /home/q672126/project/omni3d/train # train_on_one_category
    split: train
    img_size: [420, 420] # image resolution, [852,1096]
    n_group: ${n_views}
    voxel_reso: ${voxel_reso}
    n_scenes: 42
    load_normal: True
    positional_labelling: False
    clip_labelling: True
    labelling_dimension: 128

test_dataset:
    dataset_name: custom # shapenet_temp housecat6d
    data_root: /home/q672126/project/omni3d/val # val_on_one_category
    split: test
    img_size: [420, 420]
    n_group: ${n_views}
    voxel_reso: ${voxel_reso}
    n_scenes: 42
    load_normal: True
    positional_labelling: False
    clip_labelling: True
    labelling_dimension: 128

train:
    batch_size: 3
    lr: 1e-4
    beta1: 0.9
    beta2: 0.95
    weight_decay: 0.05
    # betas: [0.9, 0.95]
    warmup_iters: 0
    n_epoch: 5000
    limit_train_batches: 1.0 # 0.2
    limit_val_batches: 1.0 # 0.02
    save_ckpt_every_n_epoch: 200
    check_val_every_n_epoch: 5
    log_train_every_n_step: 400
    start_save: 1500
    start_fine: 1500
    lambda_normal: 0.1
    start_normal: 3000
test:
    batch_size: 3
    log_val_every_n_step: 1

logger: 
    name: wandb
    dir: logs/${exp_name}
